spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    #show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: true
        page-parameter: page
        size-parameter: size
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
      enabled: true
server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
logging:
  level:
    org.prof.it.soft: DEBUG
