services:
  testing-db:
    image: postgres:16
    container_name: postgres-container-testing-db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: testing_instance
    ports:
      - "5433:5432"