services:
  client-backend:
    container_name: spring-application
    image: client:0.0.6
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://service-db:5432/profitsoft
      SPRING_DATASOURCE_USERNAME: vladyslav
      SPRING_DATASOURCE_PASSWORD: postgres
  service-db:
    image: postgres:16
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: vladyslav
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profitsoft
    ports:
      - "5432:5432"